Update overview.rst
HorizenOfficial/developer-horizen-global pull request #21
Opened 2020-08-21 02:55 UTC by ldehaan9

2020-09-01 08:00 UTC, mauriziobinello requested changes
please open your pr against the development branch, and not master.

2020-09-01 15:01 UTC, ldehaan9 commented
Hi Maurizio,
If you think the changes I suggested are worthwhile, and you'd like me to review other documents, please feel free to send me the URLs and I'll take a look. Have a good day; be well.
 Laurens 

    On Tuesday, September 1, 2020, 01:01:14 AM PDT, Maurizio Binello <notifications@github.com> wrote:  
 
 


@mauriziobinello requested changes on this pull request.

please open your pr against the development branch, and not master.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-09-03 21:16 UTC, Horusfeathers reviewed
@zennermac review completed.

2020-09-03 21:16 UTC, Horusfeathers commented on docs/introduction/overview.rst
> +| This tutorial offers Java developers all the information needed to build a complete blockchain application on the Horizen Sidechain system.
@zennermac LGTM

2020-09-03 21:16 UTC, Horusfeathers commented on docs/introduction/overview.rst
> +So, you should be comfortable with concepts such as Transactions, UTXO's, Blocks, Validation, Confirmation, Consensus, Unique Chain, Chain Forks, Hash Function, Private/Public key, and Signing, along
@zennermac 

You should be comfortable with concepts like transactions, UTXO's, blocks, validation, confirmation, consensus, unique chains, chain forks, hash functions, private/public key,s and signing, along with the concept of a network of nodes and node communication.

2020-09-03 21:16 UTC, Horusfeathers commented on docs/introduction/overview.rst
> +If the above words are new to you, you can start by exploring the Horizen Academy website's material (`link <https://academy.horizen.global/>`_). Also, the original whitepaper by Satoshi Nakamoto, "B
If the above terms are new to you, you can start by exploring the Horizen Academy website's material (`link <https://academy.horizen.global/>`_). Also, the original whitepaper by Satoshi Nakamoto, "Bitcoin: A Peer-to-Peer Electronic Cash System" (`link <https://bitcoin.org/bitcoin.pdf>`_), can be a good starting point. Direct experience with an existing blockchain software is also useful. For that, you can install the Horizen zend software from (`Github <https://github.com/HorizenOfficial/zen>`_), and explore its RPC command interface and "regtest" mode.

2020-09-03 21:59 UTC, zennermac requested changes
> please open your pr against the development branch, and not master.

Please see the comments left by @Horusfeathers and make the requested changes.

2020-09-07 14:20 UTC, merged