Logging configuration help
HorizenOfficial/developer-horizen-global pull request #65
Opened 2022-06-23 14:52 UTC by paolocappelletti

2022-06-23 15:00 UTC, paolocappelletti commented
see also this related PR: https://github.com/HorizenOfficial/Sidechains-SDK/pull/418

2022-06-24 12:51 UTC, MarcoOl94 requested changes

2022-06-24 12:51 UTC, MarcoOl94 commented on docs/introduction/Sidechain-SDK-extension.rst
> +You can rely on the default logging configuration (based on Log4J library) and change just a few parameters inside the application config file, or ovveride it completely with a custom one.
config -> configuration

2022-06-24 12:51 UTC, MarcoOl94 commented on docs/introduction/Sidechain-SDK-extension.rst
> +The following dynamic parameters coming from the application conf file are used, so that you can change them by just updating the application conf file:
We repeat twice "application conf", maybe we can rephrase in something like "The following dynamic parameters are taken from the application configuration file but you can change them at any time."

2022-06-24 12:51 UTC, MarcoOl94 commented on docs/introduction/Sidechain-SDK-extension.rst
> +- ``scorex.logDir``: base folder where log files are generated, injected in the log4jxml in the placeholder ``${sys:logDir}``
"where log files" -> "where the log files"

2022-06-24 13:07 UTC, i-Alex requested changes

2022-06-24 13:07 UTC, i-Alex commented on docs/introduction/Sidechain-SDK-extension.rst
> +You can rely on the default logging configuration (based on Log4J library) and change just a few parameters inside the application config file, or ovveride it completely with a custom one.
ovveride -> override

2022-06-27 09:22 UTC, i-Alex approved these changes

2022-06-27 12:37 UTC, MarcoOl94 approved these changes

2022-07-06 13:52 UTC, merged